language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t edan13l/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true edan13l/docker-react npm run test  -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  name: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-2-671919719178"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
